/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        transparent: 'transparent',
        current: 'currentColor',
        brik: '#FF1C6D',
        'brik-fill': '#FF1C6D',
        'background-brik': '#121317',
        'brik-overlay': '#121317B2',
        'brik-surface': '#1F2125',
        'brik-surface-2': '#2A2B30',
        'brik-surface-3': '#363940',
        'brik-disabled': '#5E5B5B',
        'brik-disabled-2': '#A3A3A3',
        primary: '#EBEBEB',
        white: '#EBEBEB',
        'brik-white-primary': '#FFF',
        'brik-white-secondary': '#EAE6E7',
        'brik-tertiary-white': '#8D888A',
        'brik-extra-white': '#FDFDFD',
        'brik-extra-white-secondary': '#C4C4C4',
        'brik-extra-white-tertiary': '#F6F6F6',
        'brik-green': '#1DC288',
        'brik-error': '#FF2E00',
        'brik-verify': '#42B919',
        'brik-black': '#121317',
        'brik-gray-primary': '#A6A6A6',
        'brik-gray-secondary': '#2D3037',
        'brik-gray-tertiary': '#363940',
      },
    },
  },
  plugins: [],
};
